spring.application.name=Ecommerce-backend
server.port=8081

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://root:pplIjYSrWZLTjgfVpxkmVhEwcGDDawVk@interchange.proxy.rlwy.net:42890/railway
spring.datasource.username=root
spring.datasource.password=pplIjYSrWZLTjgfVpxkmVhEwcGDDawVk

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8081}

